"""Stage 7b: bake a scene's runtime assets and stamp the viewer.

Three independent products, each keyed by a fingerprint of its inputs so a
re-run with the same inputs does no work:

* surfaces  - terrain, asphalt and sidewalks: data/<site>/surfaces-<hash>.bin.gz
              + surfaces.json, generated by web/precompute.html in headless Chromium
* stream    - camera-sector geometry chunks: data/<site>/stream/, produced by
              `node web/prepare_streaming.mjs`
* viewer    - the `?v=` cache stamps in index.html, from a hash of src/

`--check` needs only the standard library and no browser: Cloudflare runs it
before every deploy and it must report "current" for the committed data.
"""
import argparse
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time

from .paths import ROOT, site_paths

WEB = Path(__file__).resolve().parent / 'web'
# The bake pages are fingerprinted byte-for-byte into every baked asset
# (surfaces.json / stream manifest sourceSha256); editing one forces a re-bake.
SURFACE_PAGE = WEB / 'precompute.html'
STREAM_SCRIPT = WEB / 'prepare_streaming.mjs'
SERVER_PORT = 8734


def digest(data):
    return hashlib.sha256(data).hexdigest()


def atomic_bytes(path, data):
    path = Path(path)
    tmp = path.with_name(f'.{path.name}.{os.getpid()}.tmp')
    try:
        tmp.write_bytes(data)
        tmp.replace(path)
    finally:
        tmp.unlink(missing_ok=True)


# --- surfaces -----------------------------------------------------------------

def surface_source_hash(root=ROOT):
    """Fingerprint of the surface generator: src/*.js plus the precompute page."""
    files = [(p.relative_to(root).as_posix(), p) for p in sorted((Path(root) / 'src').glob('*.js'))]
    files.append((SURFACE_PAGE.relative_to(ROOT).as_posix(), SURFACE_PAGE))
    return digest(b''.join(label.encode() + b'\0' + path.read_bytes() for label, path in files))


def surfaces_status(paths):
    """(current, manifest, input_hash, source_hash) for one site's baked surfaces."""
    input_hash, generator_hash = digest(paths.scene.read_bytes()), surface_source_hash(paths.root)
    try:
        manifest = json.loads(paths.surfaces_index.read_text())
        current = (manifest['inputSha256'] == input_hash and manifest['sourceSha256'] == generator_hash
                   and digest((paths.data / manifest['file']).read_bytes()) == manifest['compressedSha256'])
    except (OSError, KeyError, ValueError):
        manifest, current = None, False
    return current, manifest, input_hash, generator_hash


def bake_surfaces(paths, check=False):
    current, manifest, input_hash, generator_hash = surfaces_status(paths)
    if current:
        print(f'{paths.name}: surfaces are current ({manifest["compressedBytes"] / 1e6:.2f} MB)')
        return True
    if check:
        print(f'{paths.name}: surfaces are stale; run town bake {paths.name}', file=sys.stderr)
        return False
    # Only an actual build needs the browser; --check is standard library only.
    from . import browser
    scene_bytes = paths.scene.read_bytes()
    browser.ensure_browser()
    browser.ensure_server(SERVER_PORT)
    with browser.Tab(400, 300) as tab:
        tab.go(f'http://localhost:{SERVER_PORT}/{SURFACE_PAGE.relative_to(ROOT).as_posix()}')
        deadline = time.monotonic() + 60
        while not tab.ev('typeof window.precomputeSurfaces === "function"'):
            if time.monotonic() > deadline:
                raise RuntimeError('Surface builder did not initialize: ' + '\n'.join(tab.logs))
            time.sleep(0.2)
        url = '/' + paths.relative(paths.scene)
        result = tab.ev(f'window.precomputeSurfaces({json.dumps(url)}, {json.dumps(paths.name)})')
    compressed = base64.b64decode(result.pop('base64'), validate=True)
    # An ongoing map edit must not publish assets for an obsolete snapshot.
    if paths.scene.read_bytes() != scene_bytes or surface_source_hash(paths.root) != generator_hash:
        raise RuntimeError('Map or generator changed during precompute; rerun for the current version')
    content_hash = digest(compressed)
    result.update(file=paths.surfaces(content_hash[:16]).name, inputSha256=input_hash,
                  sourceSha256=generator_hash, compressedSha256=content_hash)
    atomic_bytes(paths.data / result['file'], compressed)
    atomic_bytes(paths.surfaces_index, (json.dumps(result, indent=2) + '\n').encode())
    # Only one asset revision per site; no accumulation in the deployed app.
    for old in paths.data.glob('surfaces-*.bin.gz'):
        if old.name != result['file']:
            old.unlink()
    print(json.dumps({k: v for k, v in result.items()
                      if k not in ('key', 'sha256', 'inputSha256', 'sourceSha256', 'compressedSha256')}, indent=2))
    return True


# --- streaming ----------------------------------------------------------------

def bake_stream(paths, check=False, force=False):
    command = ['node', str(STREAM_SCRIPT), paths.relative(paths.data)]
    if check:
        command.append('--check')
    elif force:
        command.append('--force')
    return subprocess.run(command, cwd=paths.root).returncode == 0


# --- the verb -----------------------------------------------------------------

def bake(paths, *, check=False, surfaces=True, stream=True, force=False):
    """Bake one site's runtime assets; with check=True only report whether they are current.

    Assets whose fingerprints already match are left alone (exports are not
    byte-reproducible, so rebuilding them would only churn the repository);
    force=True re-exports the streaming chunks anyway.
    """
    ok = True
    if surfaces:
        ok = bake_surfaces(paths, check) and ok
    if stream:
        ok = bake_stream(paths, check, force) and ok
    return ok


# --- viewer version stamps ----------------------------------------------------

def versioned_html(root=ROOT):
    """(revision, index.html text) with every local module URL stamped `?v=<revision>`."""
    root = Path(root)
    sources = sorted(p for p in (root / 'src').iterdir() if p.suffix in ('.js', '.css'))
    hasher = hashlib.sha256()
    for path in sources:
        hasher.update(path.name.encode() + b'\0' + path.read_bytes())
    revision = hasher.hexdigest()[:16]
    html = (root / 'index.html').read_text()
    match = re.search(r'(<script type="importmap">)(.*?)(</script>)', html, re.S)
    if not match:
        raise ValueError('Missing viewer import map')
    imports = json.loads(match[2])
    imports['imports'] = {k: v for k, v in imports['imports'].items() if not k.startswith('./src/')}
    for path in sources:
        if path.suffix == '.js':
            url = './src/' + path.name
            imports['imports'][url] = f'{url}?v={revision}'
    body = '\n' + '\n'.join('    ' + line for line in json.dumps(imports, indent=2).splitlines()) + '\n  '
    html = html[:match.start(2)] + body + html[match.end(2):]
    # Script entries and modulepreload links bypass import-map resolution.
    # Match their URLs to the map so the early data entry runs exactly once.
    html = re.sub(r'((?:src|href)="\./src/[^"?]+)(?:\?[^\"]*)?"', lambda m: f'{m[1]}?v={revision}"', html)
    return revision, html


def viewer_revision(root=ROOT):
    return versioned_html(root)[0]


def stamp_viewer(root=ROOT, check=False):
    """Rewrite index.html's `?v=` stamps; with check=True only report whether they are current."""
    root = Path(root)
    revision, expected = versioned_html(root)
    path = root / 'index.html'
    if path.read_text() == expected:
        print(f'Viewer revision: {revision}')
        return True
    if check:
        print('Viewer URLs are stale; run town bake --viewer', file=sys.stderr)
        return False
    # A threaded preview must never serve a partly rewritten import map.
    with tempfile.NamedTemporaryFile(mode='w', dir=root, prefix='.viewer-', delete=False) as output:
        temporary = Path(output.name)
        output.write(expected)
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
    print(f'Viewer revision: {revision}')
    return True


# --- CLI ----------------------------------------------------------------------

def register(subparsers):
    parser = subparsers.add_parser('bake', help='bake surfaces and streaming chunks for a site, or stamp the viewer',
                                   description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('site', nargs='?', help="site name or data directory, e.g. avon or data/avon")
    parser.add_argument('--check', action='store_true', help='report whether assets are current; no browser needed')
    parser.add_argument('--force', action='store_true', help='re-export streaming chunks even when they are current')
    only = parser.add_mutually_exclusive_group()
    only.add_argument('--surfaces-only', action='store_true')
    only.add_argument('--stream-only', action='store_true')
    only.add_argument('--viewer', action='store_true', help='stamp index.html module URLs instead of baking a site')
    parser.set_defaults(run=_run)


def _run(args):
    if args.viewer:
        return 0 if stamp_viewer(ROOT, check=args.check) else 1
    if not args.site:
        print('town bake: a site (or --viewer) is required', file=sys.stderr)
        return 2
    paths = site_paths(args.site)
    return 0 if bake(paths, check=args.check, surfaces=not args.stream_only, stream=not args.surfaces_only,
                     force=args.force) else 1
